# Generated by Django 5.1 on 2024-09-23 12:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_core', '0003_alter_patientprofile_status_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.datetime.today)),
                ('end_time', models.TimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='Staff',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='time',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='time_slots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medconnect_core.time_slots'),
        ),
        migrations.AddField(
            model_name='shift',
            name='staff',
            field=models.ManyToManyField(null=True, to='medconnect_core.patientprofile'),
        ),
    ]
