# Generated by Django 5.1 on 2024-09-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_core', '0004_time_slots_remove_shift_staff_remove_shift_doctor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time_Slots',
            new_name='Time_Slot',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='time_slots',
            new_name='time_slot',
        ),
    ]
