# Generated by Django 5.1 on 2024-09-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_core', '0005_rename_time_slots_time_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='staff',
            field=models.ManyToManyField(limit_choices_to={'is_staff': True}, null=True, to='medconnect_core.patientprofile'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('ONGOING', 'Ongoing')], default='SCHEDULED', max_length=20),
        ),
    ]
