# Generated by Django 5.1 on 2024-09-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_core', '0007_alter_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
