# Generated by Django 5.1 on 2024-09-23 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_core', '0008_remove_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'status': 'Doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='medconnect_core.patientprofile'),
        ),
    ]
