# Generated by Django 5.1 on 2024-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_core', '0009_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='is_staff',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse')], max_length=100),
        ),
    ]
