# Generated by Django 5.1 on 2024-09-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_core', '0010_alter_patientprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='is_staff',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse')], max_length=100, null=True),
        ),
    ]
