# Generated by Django 5.1 on 2024-09-26 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_core', '0011_alter_patientprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medconnect_core.patientprofile'),
        ),
    ]
