# Generated by Django 5.1 on 2024-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_core', '0012_alter_session_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='is_staff',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
