# Generated by Django 5.1 on 2024-10-06 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_core', '0013_alter_patientprofile_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='medconnect_core.patientprofile'),
        ),
        migrations.AlterField(
            model_name='session',
            name='patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='medconnect_core.patientprofile'),
        ),
    ]
