# Generated by Django 5.1 on 2024-10-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_core', '0015_session_date_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse')], default='Nurse', max_length=100, null=True),
        ),
    ]
